# Generated by Django 4.2.2 on 2023-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='likedislike',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='stories',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
